#######################################################################
# Homework Assignment 5, for EECS 22, Winter 2024
#
# Initial author: Tim Schmidt
#
# Makefile: Makefile for HW 5
#
#######################################################################

# Variables

# Default target

######################### Generate object files #######################
# Target for MovieLab.o

# Target for FileIO.o

# Target for DIPs.o

# Target for Image.o

# Target for ImageList.o

# Target for Movie.o

######################### Generate the executable #####################
# Target for MovieLab

###############################  others  ##############################
# Target for clean-up
